DEMO_CASES = {
    "Typical PCOS": {
        "age": 27,
        "height_cm": 162,
        "weight_kg": 78,
        "bmi": 29.7,
        "cycle": 1,
        "cycle_length": 48,
        "weight_gain": 1,
        "hair_growth": 1,
        "skin_darkening": 1,
        "hair_loss": 0,
        "pimples": 1,
        "bp_systolic": 132,
        "bp_diastolic": 84,
        "rbs": 142,
        "tsh": 2.1,
        "prl": 18,
        "fsh": 5.1,
        "lh": 9.8,
        "hemoglobin": 12.1,
        "waist": 38,
        "hip": 42,
        "waist_hip_ratio": 0.9,
        "amh": 6.2,
        "follicle_no_l": 14,
        "follicle_no_r": 16,
        "avg_f_size_l": 17,
        "avg_f_size_r": 18,
        "endometrium": 9,
        "chronic_pelvic_pain": 2,
    },
    "Lean PCOS": {
        "age": 24,
        "height_cm": 168,
        "weight_kg": 58,
        "bmi": 20.5,
        "cycle": 1,
        "cycle_length": 42,
        "weight_gain": 0,
        "hair_growth": 1,
        "skin_darkening": 0,
        "hair_loss": 1,
        "pimples": 1,
        "tsh": 1.9,
        "prl": 14,
        "amh": 5.1,
        "follicle_no_l": 13,
        "follicle_no_r": 12,
        "chronic_pelvic_pain": 1,
    },
    "Endometriosis-like": {
        "age": 32,
        "height_cm": 160,
        "weight_kg": 61,
        "bmi": 23.8,
        "cycle": 0,
        "cycle_length": 29,
        "weight_gain": 0,
        "hair_growth": 0,
        "skin_darkening": 0,
        "hair_loss": 0,
        "pimples": 0,
        "chronic_pelvic_pain": 8,
        "severe_menstrual_pain": 1,
        "pain_with_intercourse": 1,
        "bowel_urinary_pain": 1,
        "heavy_bleeding": 1,
        "bloating_nausea": 1,
        "difficulty_conceiving": 1,
    },
    "Incomplete Data": {
        "age": 29,
        "height_cm": 165,
        "weight_kg": 70,
        "bmi": 25.7,
        "cycle": 1,
        "cycle_length": 40,
        "weight_gain": 1,
        "hair_growth": 0,
        "skin_darkening": 0,
        "hair_loss": 0,
        "pimples": 0,
        "chronic_pelvic_pain": 3,
    },
}
